language: cpp
dist: trusty

sudo: required

jobs:
  include:
  - name: "RaspberryPI"
    env: DOCKER_IMAGE=yadoms/build_for_raspberrypi${DOCKER_TAG_RPI}
  - name: "Linux"
    env: DOCKER_IMAGE=yadoms/build_for_ubuntu${DOCKER_TAG_LINUX}
  - name: "MacOSX"
    env: DOCKER_IMAGE=yadoms/build_for_macos${DOCKER_TAG_MACOS}
  - name: "Synology 218+"
    env: DOCKER_IMAGE=yadoms/build_for_synology218p${DOCKER_TAG_SYNO}
  
services:
  - docker

before_install:
  - docker pull ${DOCKER_IMAGE}
  
script:
  # make generation withtou uploading to ftp
  - docker run --name docCon -e MAKE_PACKAGE=true -e YADOMS_BUILD_BRANCH=${TRAVIS_BRANCH} ${DOCKER_IMAGE} /entrypoint.sh
  - docker cp docCon:/yadoms/builds/package .

before_deploy:
  #setting the travis tag, ensure all upload are assigned to the same draft
  - export TRAVIS_TAG=`ls package/Yadoms*.tar.gz | head -1 | grep -oP '(?<=-).*(?=-)'`
  
deploy:
  #Deploy for Github Release
  # -> create a draft for each new version
  # -> all job push to the same draft
  # -> in case of job re-run, files are overwritten
  # -> deploy is systematic (not only on tags) and for all branches
  provider: releases
  api_key: "${GH_OAUTH}"
  file_glob: true
  file: package/*
  skip_cleanup: true  
  draft: true
  overwrite: true
  on:
    all_branches: true
    
